### ISSUE TITLE
error AD0001: Analyzer 'IDisposableAnalyzers...' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Position is not within syntax tree with full span

### ISSUE THREAD

**Issue by fuocor** [DotNetAnalyzers/IDisposableAnalyzers#257]
Using version 3.4.6, this started popping up this morning.

```
     1>CSC : error AD0001: Analyzer 'IDisposableAnalyzers.LocalDeclarationAnalyzer' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Position is not within syntax tree with full span [0..18276) (Parameter 'position') [D:\ossiaco\chorus\src\Chorus.Services\src\Chorus.Services.csproj]
         Actual value was 18687.'.
         Exception occurred with following context:
         Compilation: Chorus.Services
         SyntaxTree: D:\ossiaco\chorus\src\Chorus.Services\src\Application\ChorusServerApplication.cs
         SyntaxNode: var cosmosInstance = new CosmosInstance ... [LocalDeclarationStatementSyntax]@[15373..15479) (263,16)-(263,122)
         System.ArgumentOutOfRangeException: Position is not within syntax tree with full span [0..18276) (Parameter 'position')
         Actual value was 18687.
         at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckAndAdjustPosition(Int32 position, SyntaxToken& token)
         at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.IsAccessible(Int32 position, Symbol symbol)
         at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.IsAccessibleCore(Int32 position, ISymbol symbol)
         at IDisposableAnalyzers.Disposable.AccessibleInReturnValue(Target`3 target, Recursion recursion, ExpressionSyntax& creation)
         at IDisposableAnalyzers.Disposable.Stores(ExpressionSyntax candidate, Recursion recursion, ISymbol& container)
         at IDisposableAnalyzers.Disposable.Stores[TSource,TSymbol,TNode](Target`3 target, Recursion recursion, ISymbol& container)
         at IDisposableAnalyzers.Disposable.Stores(ExpressionSyntax candidate, Recursion recursion, ISymbol& container)
         at IDisposableAnalyzers.Disposable.ShouldDispose(LocalOrParameter localOrParameter, SemanticModel semanticModel, CancellationToken cancellationToken)
         at IDisposableAnalyzers.LocalDeclarationAnalyzer.Handle(SyntaxNodeAnalysisContext context)
         at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
         at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
         -----
         Suppress the following diagnostics to disable this analyzer: IDISP001, IDISP007
     1>CSC : error AD0001: Analyzer 'IDisposableAnalyzers.CreationAnalyzer' threw an exception of type 'System.ArgumentOutOfRangeException' with message 'Position is not within syntax tree with full span [0..18276) (Parameter 'position') [D:\ossiaco\chorus\src\Chorus.Services\src\Chorus.Services.csproj]
         Actual value was 18687.'.
         Exception occurred with following context:
         Compilation: Chorus.Services
         SyntaxTree: D:\ossiaco\chorus\src\Chorus.Services\src\Application\ChorusServerApplication.cs
         SyntaxNode: new CosmosInstance(cosmosConnection ... [ObjectCreationExpressionSyntax]@[15394..15478) (263,37)-(263,121)
         System.ArgumentOutOfRangeException: Position is not within syntax tree with full span [0..18276) (Parameter 'position')
         Actual value was 18687.
         at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckAndAdjustPosition(Int32 position, SyntaxToken& token)
         at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.IsAccessible(Int32 position, Symbol symbol)
         at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.IsAccessibleCore(Int32 position, ISymbol symbol)
         at IDisposableAnalyzers.Disposable.AccessibleInReturnValue(Target`3 target, Recursion recursion, ExpressionSyntax& creation)
         at IDisposableAnalyzers.Disposable.Stores(ExpressionSyntax candidate, Recursion recursion, ISymbol& container)
         at IDisposableAnalyzers.Disposable.Stores[TSource,TSymbol,TNode](Target`3 target, Recursion recursion, ISymbol& container)
         at IDisposableAnalyzers.Disposable.Stores(ExpressionSyntax candidate, Recursion recursion, ISymbol& container)
         at IDisposableAnalyzers.Disposable.Stores[TSource,TSymbol,TNode](Target`3 target, Recursion recursion, ISymbol& container)
         at IDisposableAnalyzers.Disposable.Stores(ExpressionSyntax candidate, Recursion recursion, ISymbol& container)
         at IDisposableAnalyzers.Disposable.Ignores(ExpressionSyntax candidate, Recursion recursion)
         at IDisposableAnalyzers.Disposable.Ignores(ExpressionSyntax candidate, SemanticModel semanticModel, CancellationToken cancellationToken)
         at IDisposableAnalyzers.CreationAnalyzer.Handle(SyntaxNodeAnalysisContext context)
         at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.<>c__62`1.<ExecuteSyntaxNodeAction>b__62_0(ValueTuple`2 data)
         at Microsoft.CodeAnalysis.Diagnostics.AnalyzerExecutor.ExecuteAndCatchIfThrows_NoLock[TArg](DiagnosticAnalyzer analyzer, Action`1 analyze, TArg argument, Nullable`1 info)
         -----
         Suppress the following diagnostics to disable this analyzer: IDISP004, IDISP014
```

the offending line was 
```csharp
var cosmosInstance = new CosmosInstance(cosmosConnection.CosmosClient, cosmosOptions, this.loggerFactory);
```
changing to:

```csharp
var cosmosInstance = CosmosInstance.CreateInstance(cosmosConnection.CosmosClient, cosmosOptions, this.loggerFactory);
```

with the latter, the disposable return is not detected by the analyzer but no crash.

Attached is the detailed build log.
[msbuild.zip](https://github.com/DotNetAnalyzers/IDisposableAnalyzers/files/5636603/msbuild.zip)

**Comment by JohanLarsson** [comment]
Thanks for reporting!
Not sure what I'm dumbing here but the repro code can hopefully help.

**Comment by JohanLarsson** [comment]
```
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.CheckAndAdjustPosition(Int32 position, SyntaxToken& token)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.IsAccessible(Int32 position, Symbol symbol)
   at Microsoft.CodeAnalysis.CSharp.CSharpSemanticModel.IsAccessibleCore(Int32 position, ISymbol symbol)
   at Microsoft.CodeAnalysis.SemanticModel.IsAccessible(Int32 position, ISymbol symbol)
   ```
   
   It throws deep inside Roslyn, this may be a tricky one to fix/hack around.

**Comment by JohanLarsson** [comment]
https://www.nuget.org/packages/IDisposableAnalyzers/3.4.9
